menu:
    Blog: /
    Archive: /archives/
    project: https://github.com/leer0911/Project/blob/master/README.md
    GitHub: https://github.com/leer0911
    Design: http://www.zcool.com.cn/u/1433785
favicon: /logo.png
logo: /logo.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: UA-65933410-1

# Copyright Infomation
startyear: 2016
